services:
  - type: web
    name: Visitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: TZ
        value: Asia/Kolkata
      - key: PORT
        value: 10000
